defmodule FounderPad.Repo.Migrations.CreatePrivacy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:deletion_requests, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:status, :text, null: false, default: "pending")
      add(:confirmation_token, :text)
      add(:confirmed_at, :utc_datetime_usec)
      add(:soft_deleted_at, :utc_datetime_usec)
      add(:hard_delete_after, :utc_datetime_usec)
      add(:hard_deleted_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "deletion_requests_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:data_export_requests, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:status, :text, null: false, default: "pending")
      add(:file_path, :text)
      add(:expires_at, :utc_datetime_usec)
      add(:completed_at, :utc_datetime_usec)
      add(:error, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "data_export_requests_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:cookie_consents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:consent_id, :text, null: false)
      add(:analytics, :boolean, default: false)
      add(:marketing, :boolean, default: false)
      add(:functional, :boolean, default: true)
      add(:ip_address, :text)
      add(:user_agent, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "cookie_consents_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:cookie_consents, "cookie_consents_user_id_fkey"))

    drop(table(:cookie_consents))

    drop(constraint(:data_export_requests, "data_export_requests_user_id_fkey"))

    drop(table(:data_export_requests))

    drop(constraint(:deletion_requests, "deletion_requests_user_id_fkey"))

    drop(table(:deletion_requests))
  end
end
