defmodule LinkHub.Repo.Migrations.AddQuotasContextsLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:storage_quotas, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:used_bytes, :bigint, null: false, default: 0)
      add(:quota_bytes, :bigint)
      add(:file_count, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :workspace_id,
        references(:workspaces,
          column: :id,
          name: "storage_quotas_workspace_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:storage_quotas, [:workspace_id],
        name: "storage_quotas_unique_workspace_index"
      )
    )

    create table(:share_links, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:token, :text, null: false)
      add(:password_hash, :text)
      add(:expires_at, :utc_datetime_usec)
      add(:max_downloads, :bigint)
      add(:download_count, :bigint, null: false, default: 0)
      add(:active, :boolean, null: false, default: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :stored_file_id,
        references(:stored_files,
          column: :id,
          name: "share_links_stored_file_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :created_by_id,
        references(:users,
          column: :id,
          name: "share_links_created_by_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(unique_index(:share_links, [:token], name: "share_links_unique_token_index"))

    create table(:file_contexts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:context_type, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :stored_file_id,
        references(:stored_files,
          column: :id,
          name: "file_contexts_stored_file_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :channel_id,
        references(:channels,
          column: :id,
          name: "file_contexts_channel_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :message_id,
        references(:messages,
          column: :id,
          name: "file_contexts_message_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(
      unique_index(:file_contexts, [:stored_file_id, :message_id],
        name: "file_contexts_unique_file_message_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:file_contexts, [:stored_file_id, :message_id],
        name: "file_contexts_unique_file_message_index"
      )
    )

    drop(constraint(:file_contexts, "file_contexts_stored_file_id_fkey"))

    drop(constraint(:file_contexts, "file_contexts_channel_id_fkey"))

    drop(constraint(:file_contexts, "file_contexts_message_id_fkey"))

    drop(table(:file_contexts))

    drop_if_exists(unique_index(:share_links, [:token], name: "share_links_unique_token_index"))

    drop(constraint(:share_links, "share_links_stored_file_id_fkey"))

    drop(constraint(:share_links, "share_links_created_by_id_fkey"))

    drop(table(:share_links))

    drop_if_exists(
      unique_index(:storage_quotas, [:workspace_id],
        name: "storage_quotas_unique_workspace_index"
      )
    )

    drop(constraint(:storage_quotas, "storage_quotas_workspace_id_fkey"))

    drop(table(:storage_quotas))
  end
end
