defmodule FounderPad.Repo.Migrations.AddModeToApiKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:api_keys) do
      add(:mode, :text, null: false, default: "test")
    end
  end

  def down do
    alter table(:api_keys) do
      remove(:mode)
    end
  end
end
