defmodule FounderPad.Repo.Migrations.CreateReviewCases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:review_cases, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:subject_type, :text, null: false)
      add(:subject_id, :uuid, null: false)
      add(:status, :text, null: false, default: "open")
      add(:priority, :text, null: false, default: "normal")
      add(:assigned_to_user_id, :uuid)
      add(:decision_reason, :text)
      add(:closed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "review_cases_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:review_notes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:body, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :review_case_id,
        references(:review_cases,
          column: :id,
          name: "review_notes_review_case_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "review_notes_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:review_notes, "review_notes_review_case_id_fkey"))

    drop(constraint(:review_notes, "review_notes_user_id_fkey"))

    drop(table(:review_notes))

    drop(constraint(:review_cases, "review_cases_organisation_id_fkey"))

    drop(table(:review_cases))
  end
end
