defmodule FounderPad.Repo.Migrations.AddSuspendedAtToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add(:suspended_at, :utc_datetime_usec)
    end

    create table(:api_keys, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:key_prefix, :text, null: false)
      add(:key_hash, :text, null: false)
      add(:scopes, {:array, :text}, null: false)
      add(:last_used_at, :utc_datetime_usec)
      add(:expires_at, :utc_datetime_usec)
      add(:revoked_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "api_keys_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :created_by_id,
        references(:users,
          column: :id,
          name: "api_keys_created_by_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(unique_index(:api_keys, [:key_hash], name: "api_keys_unique_key_hash_index"))

    create table(:api_key_usage, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:endpoint, :text)
      add(:method, :text)
      add(:status_code, :bigint)
      add(:response_time_ms, :bigint)
      add(:ip_address, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :api_key_id,
        references(:api_keys,
          column: :id,
          name: "api_key_usage_api_key_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:api_key_usage, "api_key_usage_api_key_id_fkey"))

    drop(table(:api_key_usage))

    drop_if_exists(unique_index(:api_keys, [:key_hash], name: "api_keys_unique_key_hash_index"))

    drop(constraint(:api_keys, "api_keys_organisation_id_fkey"))

    drop(constraint(:api_keys, "api_keys_created_by_id_fkey"))

    drop(table(:api_keys))

    alter table(:users) do
      remove(:suspended_at)
    end
  end
end
