defmodule FounderPad.Repo.Migrations.CreateIdempotencyKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:idempotency_keys, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:key, :text, null: false)
      add(:request_fingerprint, :text, null: false)
      add(:response_status, :bigint, null: false)
      add(:response_body, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "idempotency_keys_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:idempotency_keys, [:organisation_id, :key],
        name: "idempotency_keys_unique_key_per_org_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:idempotency_keys, [:organisation_id, :key],
        name: "idempotency_keys_unique_key_per_org_index"
      )
    )

    drop(constraint(:idempotency_keys, "idempotency_keys_organisation_id_fkey"))

    drop(table(:idempotency_keys))
  end
end
