defmodule FounderPad.Repo.Migrations.CreateHelpCenter do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:help_contact_requests, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:email, :text, null: false)
      add(:subject, :text, null: false)
      add(:message, :text, null: false)
      add(:status, :text, null: false, default: "new")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:help_categories, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:slug, :text, null: false)
      add(:description, :text)
      add(:icon, :text, default: "help")
      add(:position, :bigint, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:help_categories, [:slug], name: "help_categories_unique_slug_index"))

    create table(:help_articles, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:slug, :text, null: false)
      add(:body, :text, null: false)
      add(:excerpt, :text)
      add(:help_context_key, :text)
      add(:status, :text, null: false, default: "draft")
      add(:position, :bigint, default: 0)
      add(:published_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :category_id,
        references(:help_categories,
          column: :id,
          name: "help_articles_category_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:help_articles, [:category_id, :slug],
        name: "help_articles_unique_slug_per_category_index"
      )
    )

    execute """
    CREATE INDEX help_articles_search_idx ON help_articles
    USING GIN (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(excerpt, '') || ' ' || coalesce(body, '')));
    """
  end

  def down do
    drop_if_exists(
      unique_index(:help_articles, [:category_id, :slug],
        name: "help_articles_unique_slug_per_category_index"
      )
    )

    drop(constraint(:help_articles, "help_articles_category_id_fkey"))

    drop(table(:help_articles))

    drop_if_exists(
      unique_index(:help_categories, [:slug], name: "help_categories_unique_slug_index")
    )

    drop(table(:help_categories))

    drop(table(:help_contact_requests))
  end
end
