defmodule FounderPad.Repo.Migrations.CreateLivenessChecks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:liveness_checks, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:provider_name, :text)
      add(:provider_reference, :text)
      add(:status, :text, null: false, default: "pending")
      add(:confidence_score, :decimal)
      add(:reason_codes, {:array, :text}, default: [])

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "liveness_checks_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :individual_verification_id,
        references(:individual_verifications,
          column: :id,
          name: "liveness_checks_individual_verification_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:liveness_checks, "liveness_checks_organisation_id_fkey"))

    drop(constraint(:liveness_checks, "liveness_checks_individual_verification_id_fkey"))

    drop(table(:liveness_checks))
  end
end
