defmodule FounderPad.Repo.Migrations.CreateBilling do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:usage_records, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:event_type, :text, null: false)
      add(:quantity, :bigint, null: false, default: 1)
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "usage_records_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:subscriptions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:stripe_subscription_id, :text, null: false)
      add(:stripe_customer_id, :text, null: false)
      add(:status, :text, null: false, default: "active")
      add(:current_period_start, :utc_datetime)
      add(:current_period_end, :utc_datetime)
      add(:cancel_at_period_end, :boolean, default: false)
      add(:canceled_at, :utc_datetime)
      add(:trial_end, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "subscriptions_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:plan_id, :uuid, null: false)
    end

    create table(:plans, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:subscriptions) do
      modify(
        :plan_id,
        references(:plans,
          column: :id,
          name: "subscriptions_plan_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(
      unique_index(:subscriptions, [:stripe_subscription_id],
        name: "subscriptions_unique_stripe_subscription_index"
      )
    )

    alter table(:plans) do
      add(:name, :text, null: false)
      add(:slug, :text, null: false)
      add(:stripe_product_id, :text, null: false)
      add(:stripe_price_id, :text, null: false)
      add(:price_cents, :bigint, null: false, default: 0)
      add(:interval, :text, null: false, default: "monthly")
      add(:features, {:array, :text}, default: [])
      add(:max_seats, :bigint, default: 5)
      add(:max_agents, :bigint, default: 3)
      add(:max_api_calls_per_month, :bigint, default: 1000)
      add(:active, :boolean, default: true)
      add(:sort_order, :bigint, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:plans, [:slug], name: "plans_unique_slug_index"))

    create(unique_index(:plans, [:stripe_product_id], name: "plans_unique_stripe_product_index"))
  end

  def down do
    drop_if_exists(
      unique_index(:plans, [:stripe_product_id], name: "plans_unique_stripe_product_index")
    )

    drop_if_exists(unique_index(:plans, [:slug], name: "plans_unique_slug_index"))

    alter table(:plans) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:sort_order)
      remove(:active)
      remove(:max_api_calls_per_month)
      remove(:max_agents)
      remove(:max_seats)
      remove(:features)
      remove(:interval)
      remove(:price_cents)
      remove(:stripe_price_id)
      remove(:stripe_product_id)
      remove(:slug)
      remove(:name)
    end

    drop_if_exists(
      unique_index(:subscriptions, [:stripe_subscription_id],
        name: "subscriptions_unique_stripe_subscription_index"
      )
    )

    drop(constraint(:subscriptions, "subscriptions_plan_id_fkey"))

    alter table(:subscriptions) do
      modify(:plan_id, :uuid)
    end

    drop(table(:plans))

    drop(constraint(:subscriptions, "subscriptions_organisation_id_fkey"))

    drop(table(:subscriptions))

    drop(constraint(:usage_records, "usage_records_organisation_id_fkey"))

    drop(table(:usage_records))
  end
end
