defmodule FounderPad.Repo.Migrations.CreateAi do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tool_calls, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tool_name, :text, null: false)
      add(:input, :map, default: %{})
      add(:output, :map)
      add(:status, :text, null: false, default: "pending")
      add(:duration_ms, :bigint)
      add(:error, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:message_id, :uuid, null: false)
    end

    create table(:messages, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:tool_calls) do
      modify(
        :message_id,
        references(:messages,
          column: :id,
          name: "tool_calls_message_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:messages) do
      add(:role, :text, null: false)
      add(:content, :text, null: false)
      add(:token_count, :bigint, default: 0)
      add(:cost_cents, :bigint, default: 0)
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:conversation_id, :uuid, null: false)
    end

    create table(:conversations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:messages) do
      modify(
        :conversation_id,
        references(:conversations,
          column: :id,
          name: "messages_conversation_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:conversations) do
      add(:title, :text)
      add(:status, :text, null: false, default: "active")
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:agent_id, :uuid, null: false)
      add(:organisation_id, :uuid, null: false)
      add(:user_id, :uuid, null: false)
    end

    create table(:agents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:conversations) do
      modify(
        :agent_id,
        references(:agents,
          column: :id,
          name: "conversations_agent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "conversations_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :user_id,
        references(:users,
          column: :id,
          name: "conversations_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:agents) do
      add(:name, :text, null: false)
      add(:description, :text)
      add(:system_prompt, :text, null: false, default: "You are a helpful assistant.")
      add(:model, :text, null: false, default: "claude-sonnet-4-20250514")
      add(:provider, :text, null: false, default: "anthropic")
      add(:tools, {:array, :map}, default: [])
      add(:temperature, :float, default: 0.7)
      add(:max_tokens, :bigint, default: 4096)
      add(:active, :boolean, default: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "agents_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:agents, "agents_organisation_id_fkey"))

    alter table(:agents) do
      remove(:organisation_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:active)
      remove(:max_tokens)
      remove(:temperature)
      remove(:tools)
      remove(:provider)
      remove(:model)
      remove(:system_prompt)
      remove(:description)
      remove(:name)
    end

    drop(constraint(:conversations, "conversations_agent_id_fkey"))

    drop(constraint(:conversations, "conversations_organisation_id_fkey"))

    drop(constraint(:conversations, "conversations_user_id_fkey"))

    alter table(:conversations) do
      modify(:user_id, :uuid)
      modify(:organisation_id, :uuid)
      modify(:agent_id, :uuid)
    end

    drop(table(:agents))

    alter table(:conversations) do
      remove(:user_id)
      remove(:organisation_id)
      remove(:agent_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:metadata)
      remove(:status)
      remove(:title)
    end

    drop(constraint(:messages, "messages_conversation_id_fkey"))

    alter table(:messages) do
      modify(:conversation_id, :uuid)
    end

    drop(table(:conversations))

    alter table(:messages) do
      remove(:conversation_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:metadata)
      remove(:cost_cents)
      remove(:token_count)
      remove(:content)
      remove(:role)
    end

    drop(constraint(:tool_calls, "tool_calls_message_id_fkey"))

    alter table(:tool_calls) do
      modify(:message_id, :uuid)
    end

    drop(table(:messages))

    drop(table(:tool_calls))
  end
end
