defmodule FounderPad.Repo.Migrations.CreateAmlScreens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:aml_screens, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:subject_type, :text, null: false)
      add(:subject_id, :uuid, null: false)
      add(:provider_name, :text)
      add(:provider_reference, :text)
      add(:status, :text, null: false, default: "pending")
      add(:lists_checked, {:array, :text}, default: [])
      add(:match_count, :bigint, default: 0)
      add(:highest_confidence, :decimal)
      add(:reason_codes, {:array, :text}, default: [])

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "aml_screens_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:aml_screens, "aml_screens_organisation_id_fkey"))

    drop(table(:aml_screens))
  end
end
