defmodule LinkHub.Repo.Migrations.AddStoredFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stored_files, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:filename, :text, null: false)
      add(:content_type, :text, null: false)
      add(:size_bytes, :bigint, null: false)
      add(:storage_key, :text, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:content_hash, :text)
      add(:thumbnail_key, :text)
      add(:metadata, :map, null: false, default: %{})
      add(:virus_scan_status, :text, null: false, default: "pending")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :workspace_id,
        references(:workspaces,
          column: :id,
          name: "stored_files_workspace_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :uploader_id,
        references(:users,
          column: :id,
          name: "stored_files_uploader_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:stored_files, [:storage_key], name: "stored_files_unique_storage_key_index")
    )

    alter table(:plans) do
      add(:max_file_size_bytes, :bigint, default: 20_000_000)
      add(:max_storage_bytes, :bigint)
    end
  end

  def down do
    alter table(:plans) do
      remove(:max_storage_bytes)
      remove(:max_file_size_bytes)
    end

    drop_if_exists(
      unique_index(:stored_files, [:storage_key], name: "stored_files_unique_storage_key_index")
    )

    drop(constraint(:stored_files, "stored_files_workspace_id_fkey"))

    drop(constraint(:stored_files, "stored_files_uploader_id_fkey"))

    drop(table(:stored_files))
  end
end
