defmodule FounderPad.Repo.Migrations.CreatePushSubscriptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:push_subscriptions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:type, :text, null: false)
      add(:token, :text, null: false)
      add(:device_name, :text)
      add(:active, :boolean, null: false, default: true)
      add(:last_used_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "push_subscriptions_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:push_subscriptions, [:user_id, :token],
        name: "push_subscriptions_unique_user_token_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:push_subscriptions, [:user_id, :token],
        name: "push_subscriptions_unique_user_token_index"
      )
    )

    drop(constraint(:push_subscriptions, "push_subscriptions_user_id_fkey"))

    drop(table(:push_subscriptions))
  end
end
