defmodule FounderPad.Repo.Migrations.CreateInvoices do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:invoices, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:invoice_number, :text, null: false)
      add(:amount_cents, :bigint, null: false, default: 0)
      add(:status, :text, null: false, default: "pending")
      add(:stripe_invoice_id, :text)
      add(:period_start, :date, null: false)
      add(:period_end, :date, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "invoices_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:invoices, "invoices_organisation_id_fkey"))

    drop(table(:invoices))
  end
end
