defmodule FounderPad.Repo.Migrations.CreateWebhooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:webhook_deliveries, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:event_type, :text, null: false)
      add(:payload, :map, default: %{})
      add(:response_status, :bigint)
      add(:response_body, :text)
      add(:error, :text)
      add(:attempts, :bigint, default: 0)
      add(:status, :text, null: false, default: "pending")
      add(:delivered_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:webhook_id, :uuid, null: false)
    end

    create table(:outbound_webhooks, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:webhook_deliveries) do
      modify(
        :webhook_id,
        references(:outbound_webhooks,
          column: :id,
          name: "webhook_deliveries_webhook_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:outbound_webhooks) do
      add(:url, :text, null: false)
      add(:secret, :text, null: false)
      add(:events, {:array, :text}, null: false, default: [])
      add(:active, :boolean, default: true)
      add(:description, :text)
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "outbound_webhooks_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:outbound_webhooks, "outbound_webhooks_organisation_id_fkey"))

    alter table(:outbound_webhooks) do
      remove(:organisation_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:metadata)
      remove(:description)
      remove(:active)
      remove(:events)
      remove(:secret)
      remove(:url)
    end

    drop(constraint(:webhook_deliveries, "webhook_deliveries_webhook_id_fkey"))

    alter table(:webhook_deliveries) do
      modify(:webhook_id, :uuid)
    end

    drop(table(:outbound_webhooks))

    drop(table(:webhook_deliveries))
  end
end
