defmodule FounderPad.Repo.Migrations.AddRiskToIndividualVerifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:individual_verifications) do
      add(:risk_level, :text)
      add(:risk_score, :bigint)
    end
  end

  def down do
    alter table(:individual_verifications) do
      remove(:risk_score)
      remove(:risk_level)
    end
  end
end
