defmodule FounderPad.Repo.Migrations.CreateIndividualVerifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:individual_verifications, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:external_id, :text)
      add(:mode, :text, null: false, default: "test")
      add(:ghana_card_number_hash, :text, null: false)
      add(:first_name, :text)
      add(:last_name, :text)
      add(:date_of_birth, :date)
      add(:phone_number_hash, :text)
      add(:status, :text, null: false, default: "pending")
      add(:provider_name, :text)
      add(:provider_reference, :text)
      add(:identity_verified, :boolean, default: false)
      add(:match_level, :text, default: "none")
      add(:reason_codes, {:array, :text}, default: [])
      add(:completed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "individual_verifications_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :consent_receipt_id,
        references(:consent_receipts,
          column: :id,
          name: "individual_verifications_consent_receipt_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(
      unique_index(:individual_verifications, [:organisation_id, :external_id],
        name: "individual_verifications_unique_external_id_per_org_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:individual_verifications, [:organisation_id, :external_id],
        name: "individual_verifications_unique_external_id_per_org_index"
      )
    )

    drop(constraint(:individual_verifications, "individual_verifications_organisation_id_fkey"))

    drop(
      constraint(:individual_verifications, "individual_verifications_consent_receipt_id_fkey")
    )

    drop(table(:individual_verifications))
  end
end
