defmodule FounderPad.Repo.Migrations.CreateAuditLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_logs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:action, :text, null: false)
      add(:resource_type, :text, null: false)
      add(:resource_id, :text, null: false)
      add(:actor_id, :uuid)
      add(:organisation_id, :uuid)
      add(:changes, :map, default: %{})
      add(:metadata, :map, default: %{})
      add(:ip_address, :text)
      add(:user_agent, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    # Indexes for efficient querying
    create index(:audit_logs, [:resource_type, :resource_id])
    create index(:audit_logs, [:actor_id])
    create index(:audit_logs, [:organisation_id])
    create index(:audit_logs, [:action])
    create index(:audit_logs, [:inserted_at])
  end

  def down do
    drop(table(:audit_logs))
  end
end
