defmodule FounderPad.Repo.Migrations.AddEmailPreferencesToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add(:email_preferences, :map, null: false, default: fragment("'{\"marketing\": true, \"product_updates\": true, \"weekly_digest\": true, \"billing\": true, \"team\": true}'::jsonb"))
    end
  end

  def down do
    alter table(:users) do
      remove(:email_preferences)
    end
  end
end
