defmodule FounderPad.Repo.Migrations.CreateBusinessVerifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:business_verifications, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:external_id, :text)
      add(:mode, :text, null: false, default: "test")
      add(:registered_name, :text)
      add(:registration_number_hash, :text, null: false)
      add(:tin_hash, :text)
      add(:status, :text, null: false, default: "pending")
      add(:provider_name, :text)
      add(:provider_reference, :text)
      add(:risk_level, :text)
      add(:reason_codes, {:array, :text}, default: [])
      add(:completed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "business_verifications_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:business_verifications, [:organisation_id, :external_id],
        name: "business_verifications_unique_external_id_per_org_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:business_verifications, [:organisation_id, :external_id],
        name: "business_verifications_unique_external_id_per_org_index"
      )
    )

    drop(constraint(:business_verifications, "business_verifications_organisation_id_fkey"))

    drop(table(:business_verifications))
  end
end
