defmodule FounderPad.Repo.Migrations.CreateContentTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:changelog_entries, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version, :text, null: false)
      add(:title, :text, null: false)
      add(:body, :text)
      add(:type, :text, null: false, default: "feature")
      add(:status, :text, null: false, default: "draft")
      add(:published_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :author_id,
        references(:users,
          column: :id,
          name: "changelog_entries_author_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:blog_tags, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:slug, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:blog_tags, [:slug], name: "blog_tags_unique_slug_index"))

    create table(:blog_posts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:slug, :text, null: false)
      add(:body, :text)
      add(:excerpt, :text)
      add(:featured_image_url, :text)
      add(:status, :text, null: false, default: "draft")
      add(:published_at, :utc_datetime_usec)
      add(:scheduled_at, :utc_datetime_usec)
      add(:reading_time_minutes, :bigint, default: 1)
      add(:meta_title, :text)
      add(:meta_description, :text)
      add(:og_image_url, :text)
      add(:canonical_url, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :author_id,
        references(:users,
          column: :id,
          name: "blog_posts_author_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(unique_index(:blog_posts, [:slug], name: "blog_posts_unique_slug_index"))

    create table(:blog_post_tags, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :post_id,
        references(:blog_posts,
          column: :id,
          name: "blog_post_tags_post_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :tag_id,
        references(:blog_tags,
          column: :id,
          name: "blog_post_tags_tag_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:blog_post_tags, [:post_id, :tag_id],
        name: "blog_post_tags_unique_post_tag_index"
      )
    )

    create table(:blog_post_categories, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :post_id,
        references(:blog_posts,
          column: :id,
          name: "blog_post_categories_post_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:category_id, :uuid, null: false)
    end

    create table(:blog_categories, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:blog_post_categories) do
      modify(
        :category_id,
        references(:blog_categories,
          column: :id,
          name: "blog_post_categories_category_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(
      unique_index(:blog_post_categories, [:post_id, :category_id],
        name: "blog_post_categories_unique_post_category_index"
      )
    )

    alter table(:blog_categories) do
      add(:name, :text, null: false)
      add(:slug, :text, null: false)
      add(:description, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:blog_categories, [:slug], name: "blog_categories_unique_slug_index"))
  end

  def down do
    drop_if_exists(
      unique_index(:blog_categories, [:slug], name: "blog_categories_unique_slug_index")
    )

    alter table(:blog_categories) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:description)
      remove(:slug)
      remove(:name)
    end

    drop_if_exists(
      unique_index(:blog_post_categories, [:post_id, :category_id],
        name: "blog_post_categories_unique_post_category_index"
      )
    )

    drop(constraint(:blog_post_categories, "blog_post_categories_category_id_fkey"))

    alter table(:blog_post_categories) do
      modify(:category_id, :uuid)
    end

    drop(table(:blog_categories))

    drop(constraint(:blog_post_categories, "blog_post_categories_post_id_fkey"))

    drop(table(:blog_post_categories))

    drop_if_exists(
      unique_index(:blog_post_tags, [:post_id, :tag_id],
        name: "blog_post_tags_unique_post_tag_index"
      )
    )

    drop(constraint(:blog_post_tags, "blog_post_tags_post_id_fkey"))

    drop(constraint(:blog_post_tags, "blog_post_tags_tag_id_fkey"))

    drop(table(:blog_post_tags))

    drop_if_exists(unique_index(:blog_posts, [:slug], name: "blog_posts_unique_slug_index"))

    drop(constraint(:blog_posts, "blog_posts_author_id_fkey"))

    drop(table(:blog_posts))

    drop_if_exists(unique_index(:blog_tags, [:slug], name: "blog_tags_unique_slug_index"))

    drop(table(:blog_tags))

    drop(constraint(:changelog_entries, "changelog_entries_author_id_fkey"))

    drop(table(:changelog_entries))
  end
end
