defmodule FounderPad.Repo.Migrations.CreateEvidenceItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:evidence_items, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:type, :text, null: false)
      add(:storage_key, :text, null: false)
      add(:content_type, :text)
      add(:size_bytes, :bigint)
      add(:checksum, :text)
      add(:status, :text, null: false, default: "pending_upload")
      add(:expires_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organisation_id,
        references(:organisations,
          column: :id,
          name: "evidence_items_organisation_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :individual_verification_id,
        references(:individual_verifications,
          column: :id,
          name: "evidence_items_individual_verification_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:evidence_items, "evidence_items_organisation_id_fkey"))

    drop(constraint(:evidence_items, "evidence_items_individual_verification_id_fkey"))

    drop(table(:evidence_items))
  end
end
