defmodule FounderPad.Repo.Migrations.CreateSocialIdentities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:social_identities, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:provider, :text, null: false)
      add(:provider_uid, :text, null: false)
      add(:provider_email, :text)
      add(:provider_data, :map, default: %{})
      add(:linked_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "social_identities_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:social_identities, [:provider, :provider_uid],
        name: "social_identities_unique_provider_uid_index"
      )
    )

    create(
      unique_index(:social_identities, [:provider, :user_id],
        name: "social_identities_unique_provider_user_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:social_identities, [:provider, :user_id],
        name: "social_identities_unique_provider_user_index"
      )
    )

    drop_if_exists(
      unique_index(:social_identities, [:provider, :provider_uid],
        name: "social_identities_unique_provider_uid_index"
      )
    )

    drop(constraint(:social_identities, "social_identities_user_id_fkey"))

    drop(table(:social_identities))
  end
end
