defmodule FounderPad.Repo.Migrations.CreateAnalytics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:search_console_data, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:keyword, :text, null: false)
      add(:page, :text)
      add(:clicks, :bigint, default: 0)
      add(:impressions, :bigint, default: 0)
      add(:position, :float)
      add(:ctr, :float)
      add(:organisation_id, :uuid)
      add(:fetched_at, :utc_datetime, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:app_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:event_name, :text, null: false)
      add(:actor_id, :uuid)
      add(:organisation_id, :uuid)
      add(:metadata, :map, default: %{})
      add(:occurred_at, :utc_datetime, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:app_events))

    drop(table(:search_console_data))
  end
end
