defmodule FounderPad.Repo.Migrations.CreateNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notifications, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:type, :text, null: false)
      add(:title, :text, null: false)
      add(:body, :text)
      add(:read_at, :utc_datetime)
      add(:action_url, :text)
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "notifications_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:email_logs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:to, :text, null: false)
      add(:subject, :text, null: false)
      add(:template, :text, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:error, :text)
      add(:metadata, :map, default: %{})
      add(:sent_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "email_logs_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:email_logs, "email_logs_user_id_fkey"))

    drop(table(:email_logs))

    drop(constraint(:notifications, "notifications_user_id_fkey"))

    drop(table(:notifications))
  end
end
