defmodule FounderPad.Repo.Migrations.CreateFeatureFlags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:feature_flags, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:key, :text, null: false)
      add(:name, :text, null: false)
      add(:description, :text)
      add(:enabled, :boolean, null: false, default: true)
      add(:required_plan, :text)
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:feature_flags, [:key], name: "feature_flags_unique_key_index"))
  end

  def down do
    drop_if_exists(unique_index(:feature_flags, [:key], name: "feature_flags_unique_key_index"))

    drop(table(:feature_flags))
  end
end
